# Generated by Django 5.0.6 on 2024-05-29 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='STKPushTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant_id', models.CharField(max_length=255)),
                ('checkout_id', models.CharField(max_length=255)),
                ('result_code', models.CharField(max_length=255)),
                ('result_description', models.CharField(max_length=255)),
                ('amount', models.CharField(max_length=255)),
                ('mobile_number', models.CharField(max_length=255)),
                ('reference', models.CharField(max_length=255)),
                ('transaction_date', models.CharField(max_length=255)),
                ('balance', models.CharField(max_length=255)),
            ],
        ),
    ]
