# Generated by Django 5.0.6 on 2024-06-17 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Item 88', max_length=255)),
                ('price', models.DecimalField(decimal_places=2, default=10.0, max_digits=10)),
                ('discount', models.IntegerField(blank=True, default=5, null=True)),
                ('is_digital', models.BooleanField(blank=True, default=False, null=True)),
                ('description', models.TextField(blank=True, default='Buy emu tech products', null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='emu/items')),
                ('stock', models.IntegerField(blank=True, default=10, null=True)),
                ('slug', models.SlugField(blank=True, editable=False, max_length=5, null=True, unique=True)),
                ('seller', models.CharField(blank=True, max_length=255, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('category', models.ManyToManyField(default='shirts', related_name='items', to='emu.category')),
            ],
        ),
    ]
