# Generated by Django 5.0.6 on 2024-07-06 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emu', '0006_alter_item_name_guestcustomer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guestcustomer',
            name='user',
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(default='Item 29', max_length=255),
        ),
    ]
