# Generated by Django 5.0.6 on 2024-07-06 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emu', '0008_guestcustomer_password1_guestcustomer_password2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guestcustomer',
            name='password1',
        ),
        migrations.RemoveField(
            model_name='guestcustomer',
            name='password2',
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(default='Item 57', max_length=255),
        ),
    ]
