# Generated by Django 5.0.6 on 2024-07-07 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emu', '0009_remove_guestcustomer_password1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestcustomer',
            name='password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(default='Item 34', max_length=255),
        ),
    ]
