# Generated by Django 5.0.6 on 2024-07-07 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emu', '0010_guestcustomer_password_alter_item_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='shipping_addess',
            new_name='shipping_address',
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(default='Item 64', max_length=255),
        ),
    ]
