# Generated by Django 5.0.7 on 2024-07-11 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emu', '0011_rename_shipping_addess_order_shipping_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(default='Item 79', max_length=255),
        ),
    ]
