# Generated by Django 5.0.7 on 2024-07-11 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emu', '0012_alter_item_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='emu/items'),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(default='Item 100', max_length=255),
        ),
    ]
