# Generated by Django 5.0.6 on 2024-07-11 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emu', '0013_item_thumbnail_alter_item_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(default='Item 52', max_length=255),
        ),
    ]
