# Generated by Django 5.0.6 on 2024-07-15 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emu', '0015_alter_item_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_slug',
            field=models.SlugField(blank=True, default='', editable=False, max_length=5),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(default='Item 11', max_length=255),
        ),
    ]
