# Generated by Django 5.0.6 on 2024-07-25 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emu', '0020_alter_contact_user_alter_item_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.TextField(blank=True, help_text='Enter Your Message', null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='user',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(default='Item 79', max_length=255),
        ),
    ]
