# Generated by Django 5.0.6 on 2024-07-25 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emu', '0021_alter_contact_message_alter_contact_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='default_image',
            field=models.ImageField(blank=True, null=True, upload_to='emu/items'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email_address',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.TextField(help_text='Enter Your Message'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='user',
            field=models.CharField(help_text='Enter Your Name', max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(default='Item 58', max_length=255),
        ),
    ]
