# Generated by Django 5.0.6 on 2024-07-25 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emu', '0022_item_default_image_alter_contact_email_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='default_image',
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(default='Item 61', max_length=255),
        ),
    ]
