# Generated by Django 5.0.6 on 2024-08-11 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emu', '0024_alter_item_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(default='Item 23', max_length=255),
        ),
    ]
